### ISSUE TITLE
2.2.2版本 sha512sum 验证失败

### ISSUE THREAD

**Issue by sukanka** [Molunerfinn/PicGo#426]
## 问题类型

Bug Report
## PicGo的相关信息
v2.2.2

Linux AppImage
## 问题重现
在写PKGBUILD 的过程中我发现sha512sum始终验证失败, 后来又用服务器下载了一次,验证sha512sum, 发现和本地的一致. 因此我认为
`PicGo-2.2.2.AppImage` 的 `sha512sum` 与 `latest-linux.yml` 提供的不相符合.

```
#sha512sum PicGo-2.2.2.AppImage
e1d6bcc898ae3b42354c3c14c8146ef9d2f226a997bcde751b61b1495b0920c9534c76f49fd6e3d65e40280e086d033033c239a916b7cba1f5fb6ef037690f05  PicGo-2.2.2.AppImage
```
以下是 `latest-linux.yml` 的内容.
```
version: 2.2.2
files:
  - url: PicGo-2.2.2.AppImage
    sha512: 4da8yJiuO0I1TDwUyBRu+dLyJqmXvN51G2GxSVsJIMlTTHb0n9bj1l5AKA4IbQMwM8I5qRa3y6H1+27wN2kPBQ==
    size: 68755175
    blockMapSize: 73467
path: PicGo-2.2.2.AppImage
sha512: 4da8yJiuO0I1TDwUyBRu+dLyJqmXvN51G2GxSVsJIMlTTHb0n9bj1l5AKA4IbQMwM8I5qRa3y6H1+27wN2kPBQ==
releaseDate: '2020-01-20T07:51:30.071Z'

```
