### ISSUE TITLE
Scoop bucket维护请求

### ISSUE THREAD

**Issue by Gladtbam** [Molunerfinn/PicGo#832]
你好，我昨天在使用Scoop下载PicGO的时候发现`Scoop Extras Bucket`中的pcigo很久没有维护了，因此我自发的向[ScoopInstaller/Extras](https://github.com/ScoopInstaller/Extras)提交了一个[PR](https://github.com/ScoopInstaller/Extras/pull/7834)，但是发现release `2.3.0` 的latest.yml没有**32位**程序的 `hash`，请问能否添加一下

**Comment by Molunerfinn** [comment]
已经更新至release。感谢贡献！

```yaml
version: 2.3.0
files:
  - url: PicGo-Setup-2.3.0-x64.exe
    sha512: yB7AmmEt6Qw5gtxQjtgWIHAsV3oyiPoVrfcd6gre5/428w+S7UoaWmTVyXH6xo9gO9HNTlUcOt90I2DE2ha8Dg==
    size: 47228253
  - url: PicGo-Setup-2.3.0-ia32.exe
    sha512: P+kVtCvlZaIABcuUNh3KDZUl84sYIhOZ2lGreay7kddie9DZiDYP6hb1krjbDNZo42JlYiJMkSdmJsh+E112JQ==
    size: 45222076
path: PicGo-Setup-2.3.0-x64.exe
sha512: yB7AmmEt6Qw5gtxQjtgWIHAsV3oyiPoVrfcd6gre5/428w+S7UoaWmTVyXH6xo9gO9HNTlUcOt90I2DE2ha8Dg==
releaseDate: '2021-09-11T03:40:18.954Z'
```
